package:
  name: vmc
  version: "2.2"

source:
  url: https://github.com/vmc-project/vmc/archive/refs/tags/v2-2.tar.gz
  sha256: 6da6a32352c5a3eb62d07aed92414a0baf2793f6ec0630402e3df7fcb1b73d7b

build:
  number: 1
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root 6.40.*
  run:
    - root 6.40.*
  run_exports:
    - root 6.40.*

tests:
  - script:
      - test -f $PREFIX/lib/libVMCLibrary.so
      - test -d $PREFIX/include/vmc
