package:
  name: photospp
  version: "3.64"

source:
  url: https://gitlab.cern.ch/photospp/photospp/-/archive/v3.64/photospp-v3.64.tar.gz
  sha256: d42cb01eca6eea517dc6a729cd34db515d6894e6f4bab73072cb5a6fa9b93d63

build:
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - hepmc3
    - root
    - pythia8
    - tauloa
  run:
    - hepmc3
    - root
    - pythia8
    - tauloa

tests:
  - script:
      - test -f $PREFIX/lib/libPhotospp.so
      - test -f $PREFIX/lib/libPhotosppHepMC3.so
      - test -d $PREFIX/include/Photos
