context:
  version: "3.64"

package:
  name: photospp
  version: ${{ version }}

source:
  url: https://gitlab.cern.ch/photospp/photospp/-/archive/v${{ version }}/photospp-v${{ version }}.tar.gz
  sha256: d42cb01eca6eea517dc6a729cd34db515d6894e6f4bab73072cb5a6fa9b93d63

build:
  number: 1
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - sysroot_linux-64 2.17.*
    - autoconf
    - automake
    - libtool
    - make
  host:
    - hepmc3
    - root
    - pythia8
    - tauloa
  run:
    - hepmc3
    - root
    - pythia8
    - tauloa

tests:
  - script:
      - test -f $PREFIX/lib/libPhotospp.so
      - test -f $PREFIX/lib/libPhotosppHepMC3.so
      - test -d $PREFIX/include/Photos

about:
  homepage: https://photospp.web.cern.ch/
  repository: https://gitlab.cern.ch/photospp/photospp
  summary: C++ implementation of the PHOTOS QED radiative-corrections Monte Carlo
  description: |
    PHOTOS++ is the C++ implementation of the PHOTOS Monte Carlo
    algorithm for simulating QED bremsstrahlung corrections in decays
    of particles and resonances. It is intended to be interfaced to
    event generators such as Pythia and to event records in
    HepMC2/HepMC3 format, and is widely used in LHC experiment
    simulation chains.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - olantwin
