default_install_hook_types: ["pre-commit", "commit-msg"]
default_stages: [pre-commit, manual]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--unsafe]
- repo: https://github.com/crate-ci/committed
  rev: v1.1.11
  hooks:
  - id: committed
    name: check commit message formatting
- repo: https://github.com/adrienverge/yamllint
  rev: v1.37.1
  hooks:
  - id: yamllint
    args: [-c, .yamllint.yml]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
    files: recipes/.*/build\.sh$
    args: [--severity=warning]

ci:
  autofix_prs: true
  autoupdate_commit_msg: "chore(deps): update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
