version = 1
SPDX-PackageName = "ship-conda-recipes"
SPDX-PackageSupplier = "CERN for the benefit of the SHiP Collaboration"
SPDX-PackageDownloadLocation = "https://github.com/ShipSoft/ship-conda-recipes"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "CERN for the benefit of the SHiP Collaboration"
SPDX-License-Identifier = "BSD-3-Clause"
