package:
  name: genfit
  version: "2.3.0"

source:
  url: https://github.com/GenFit/GenFit/archive/refs/tags/02-03-00.tar.gz
  sha256: 741eb6cbfccc3403061cd4ccd62083adf3f9b187ea4236453eef777d4824b05e
  patches:
    - fix-dictionary-paths.patch

build:
  number: 3
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root
    - gtest
  run:
    - root

tests:
  - script:
      - test -f $PREFIX/lib/libgenfit2.so
      - test -f $PREFIX/include/AbsFitter.h
