package:
  name: genfit
  version: "2.3.0"

source:
  git: https://github.com/GenFit/GenFit
  tag: 02-03-00
  patches:
    - fix-dictionary-paths.patch

build:
  number: 3
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root
    - gtest
  run:
    - root

tests:
  - script:
      - test -f $PREFIX/lib/libgenfit2.so
      - test -f $PREFIX/include/AbsFitter.h
