package:
  name: rootegpythia6
  version: "0.1"

source:
  url: https://github.com/luketpickering/ROOTEGPythia6/archive/feb7c7eb8d368aee20bf1cb01f1bbfb9cfaeb6b5.tar.gz
  sha256: 891d637fe278c9f77eca14d66eaeb7d49af6d2bdef73af637fcc41783b096832
  patches:
    - fix-dictionary-paths.patch
    - fix-pythia6-private-link.patch

build:
  number: 4
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - sysroot_linux-64 2.17.*
    - cmake
    - make
  host:
    - root 6.40.*
    - pythia6
  run:
    - root 6.40.*
    - pythia6
  run_exports:
    - root 6.40.*

tests:
  - script:
      - test -f $PREFIX/lib/libEGPythia6.so
