package:
  name: rootegpythia6
  version: "0.1"

source:
  git: https://github.com/luketpickering/ROOTEGPythia6
  tag: feb7c7eb8d368aee20bf1cb01f1bbfb9cfaeb6b5

build:
  script: build.sh

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
  host:
    - root
  run:
    - root

test:
  commands:
    - test -f $PREFIX/lib/libEGPythia6.so
