package:
  name: geant3
  version: "4.5"

source:
  url: https://github.com/vmc-project/geant3/archive/refs/tags/v4-5.tar.gz
  sha256: 0fbfe4a9e50b3bc8af7efc11d2b167c341ba0ec3103ddbdf6d88736fd1f26e23

build:
  script: build.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - cmake
    - make
  host:
    - root
    - vmc
  run:
    - root
    - vmc

tests:
  - script:
      - test -f $PREFIX/lib/libgeant321.so || test -f $PREFIX/lib64/libgeant321.so
