context:
  version: "2.5.0"

package:
  name: mp-units
  version: ${{ version }}

source:
  url: https://github.com/mpusz/mp-units/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a6bd48bee699f11f0ed5b04b8c5006d15f76e6d898e058db3880554d2e47a400

build:
  number: 5
  skip:
    - win
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - sysroot_linux-64 2.17.*
    - cmake
    - make
  host:
    - gsl-lite
  run:
    - gsl-lite
  run_exports:
    - ${{ pin_subpackage('mp-units', upper_bound='x.x') }}

tests:
  - script:
      - test -d $PREFIX/include/mp-units
      - test -f $PREFIX/lib/cmake/mp-units/mp-unitsConfig.cmake

about:
  homepage: https://mpusz.github.io/mp-units/
  repository: https://github.com/mpusz/mp-units
  documentation: https://mpusz.github.io/mp-units/
  summary: Domain-correct C++ quantities and units library (ISO 80000)
  description: |
    mp-units is a modern C++ (C++20 and later) library providing
    compile-time safety for domain-specific quantities and units,
    from dimensional analysis to quantity-kind safety. Built on the
    ISO 80000 International System of Quantities, it prevents
    accidental mixing of quantities sharing the same dimension but
    representing different physical concepts and is a C++29
    standardisation candidate.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - olantwin
