context:
  version: "26.05.7"

package:
  name: fairship
  version: ${{ version }}

source:
  git: https://github.com/ShipSoft/FairShip
  rev: ab839844699bf204cf6916819d8f4b929e28c8d2

build:
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root
    - geant4
    - geant4-vmc
    - geant3
    - vmc
    - fairroot
    - faircmakemodules
    - fairlogger
    - genfit
    - rootegpythia6
    - pythia6
    - pythia8
    - evtgen
    - hepmc2
    - fmt
    - gsl
    - xerces-c
  run:
    - root
    - geant4
    - geant4-vmc
    - geant3
    - vmc
    - fairroot
    - fairlogger
    - genfit
    - rootegpythia6
    - pythia6
    - pythia8
    - evtgen
    - hepmc2
    - fmt
    - gsl
    - xerces-c

tests:
  - script:
      - test -f $PREFIX/lib/libShipData.so
      - test -d $PREFIX/include
      - test -d $PREFIX/share/FairShip/geometry
