context:
  version: "1.14.0"

package:
  name: random123
  version: ${{ version }}

source:
  url: https://github.com/DEShawResearch/random123/archive/refs/tags/v${{ version }}.tar.gz
  sha256: effafd8656b18030b2a5b995cd3650c51a7c45052e6e1c21e48b9fa7a59d926e

build:
  noarch: generic
  skip:
    - win
  script: build.sh

tests:
  - script:
      - test -f $PREFIX/include/Random123/philox.h
      - test -f $PREFIX/include/Random123/threefry.h
