package:
  name: pythia6
  version: "6.4.28"

source:
  git: https://github.com/SND-LHC/pythia6
  tag: v6.4.28-snd
  patches:
    - restore-dummy-pdflib.patch

build:
  number: 3
  script: build.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - cmake
    - make

tests:
  - script:
      - test -f $PREFIX/lib/libpythia6.so
      - test -f $PREFIX/lib/libPythia6.so
