package:
  name: pythia6
  version: "6.4.28"

source:
  url: https://github.com/SND-LHC/pythia6/archive/a918d08839df79965787e1fbf43ea16acc1e443d.tar.gz
  sha256: 3806efdb4fd1e295082f193bd0d03800d3fa904525cb82b0a9540401701711fa
  patches:
    - restore-dummy-pdflib.patch

build:
  number: 4
  script: build.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - sysroot_linux-64 2.17.*
    - cmake
    - make

tests:
  - script:
      - test -f $PREFIX/lib/libpythia6.so
      - test -f $PREFIX/lib/libPythia6.so
