#!/bin/bash -e
cmake ${CMAKE_ARGS} -S ${SRC_DIR} -B build \
    -DCMAKE_CXX_STANDARD=20 \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DGEOMODEL_USE_BUILTIN_JSON=OFF \
    -DGEOMODEL_USE_BUILTIN_XERCESC=OFF \
    -DGEOMODEL_USE_BUILTIN_EIGEN3=OFF \
    -DGEOMODEL_BUILD_TOOLS=ON \
    -DGEOMODEL_BUILD_GEOMODELG4=ON \
    -DGEOMODEL_BUILD_FULLSIMLIGHT=ON \
    -DGEOMODEL_BUILD_VISUALIZATION=OFF \
    -DGEOMODEL_BUILD_TESTING=OFF
cmake --build build --parallel ${CPU_COUNT}
cmake --install build
