context:
  version: "1.1.0"

package:
  name: gsl-lite
  version: ${{ version }}

source:
  url: https://github.com/gsl-lite/gsl-lite/archive/refs/tags/v${{ version }}.tar.gz
  sha256: bc786258eda511980942b973f5f394c854705bb0462ee46f82a8c39b5e19ea03

build:
  number: 1
  skip:
    - win
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - sysroot_linux-64 2.17.*
    - cmake
    - make

tests:
  - script:
      - test -d $PREFIX/include/gsl-lite
      - test -f $PREFIX/share/cmake/gsl-lite/gsl-liteConfig.cmake

about:
  homepage: https://gsl-lite.github.io/gsl-lite/
  repository: https://github.com/gsl-lite/gsl-lite
  summary: ISO C++ Core Guidelines Support Library implementation (C++98 and later)
  description: |
    gsl-lite is a portable, single-file, header-only library
    implementing the C++ Core Guidelines Support Library (GSL)
    specification. It targets a wide range of compilers and language
    standards from C++98 through C++23 (including CUDA) and provides
    the GSL types and utilities used for defensive programming, such
    as span, not_null, narrow, and assertion macros.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - olantwin
