context:
  version: "19.0.1"

package:
  name: fairroot
  version: ${{ version }}

source:
  url: https://github.com/FairRootGroup/FairRoot/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7aac7288bb68f7e37535638f3fd4cf60c2c6b4fc30350462f398bbb93e8eea52
  patches:
    - fix-boost-serialization.patch

build:
  number: 4
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - cmake
    - make
  host:
    - root 6.40.*
    - geant4 11.4.*
    - geant4-vmc
    - geant3
    - vmc
    - libboost-devel
    - fairlogger
    - faircmakemodules
    - yaml-cpp
    - pythia8
    - pythia6
    - evtgen
    - hepmc2
    - xerces-c
    - gsl
  run:
    - root 6.40.*
    - geant4 11.4.*
    - geant4-vmc
    - geant3
    - vmc
    - fairlogger
    - yaml-cpp
    - pythia8
    - pythia6
    - evtgen
    - hepmc2
    - xerces-c
    - gsl
  run_exports:
    - root 6.40.*
    - geant4 11.4.*

tests:
  - script:
      - test -f $PREFIX/lib/libFairTools.so
      - test -d $PREFIX/include
