package:
  name: geant4-vmc
  version: "6.7.1"

source:
  url: https://github.com/vmc-project/geant4_vmc/archive/refs/tags/v6-7-p1.tar.gz
  sha256: e1e80c78987f94d6e2f9644052a57f43946fc73309197a4c4400906d227d27ae

build:
  script: build.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root
    - vmc
    - geant4
    - vgm
    - xerces-c
  run:
    - root
    - vmc
    - geant4
    - vgm
    - xerces-c

tests:
  - script:
      - test -f $PREFIX/lib/libgeant4vmc.so
      - test -f $PREFIX/lib/libg4root.so
      - test -d $PREFIX/include/geant4vmc
