package:
  name: cetmodules
  version: "3.27.04"

source:
  url: https://github.com/FNALssi/cetmodules/archive/refs/tags/3.27.04.tar.gz
  sha256: c0d91c01b11609f2ef3b809a7f0ee1c328e69111cf6109f819833823a83a4f1d

build:
  skip:
    - win
  script: build.sh

requirements:
  build:
    - cmake
    - make

tests:
  - package_contents:
      files:
        - lib/cetmodules/cmake/cetmodulesConfig.cmake
