context:
  version: "1.0.0"

package:
  name: faircmakemodules
  version: ${{ version }}

source:
  url: https://github.com/FairRootGroup/FairCMakeModules/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ec60c31f38050c1173d512c58c684650db66736877c580936f7ecca33eeaf696

build:
  noarch: generic
  script: build.sh

requirements:
  build:
    - cmake
    - ${{ compiler('cxx') }}

tests:
  - script:
      - test -f $PREFIX/share/cmake/FairCMakeModules-1.0.0/FairCMakeModulesConfig.cmake
